version: '3.8'
services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    command: 'listen --forward-to web/webhook'
    environment:
      - STRIPE_API_KEY=$STRIPE_API_SECRET_KEY
    env_file:
      - ./.env
